// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contact.proto

package com.blemobi.sep.probuf;

public final class ContactProtos {
  private ContactProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PContactLinkInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bbproto.PContactLinkInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * 通讯录联系人的uuid
     * </pre>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * 通讯录联系人的uuid
     * </pre>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional string mobile = 2;</code>
     *
     * <pre>
     * 通讯录联系人的手机号码
     * </pre>
     */
    java.lang.String getMobile();
    /**
     * <code>optional string mobile = 2;</code>
     *
     * <pre>
     * 通讯录联系人的手机号码
     * </pre>
     */
    com.google.protobuf.ByteString
        getMobileBytes();

    /**
     * <code>optional string nickName = 3;</code>
     *
     * <pre>
     * 通讯录联系人的昵称
     * </pre>
     */
    java.lang.String getNickName();
    /**
     * <code>optional string nickName = 3;</code>
     *
     * <pre>
     * 通讯录联系人的昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <code>optional string hasLink = 4;</code>
     *
     * <pre>
     * 通讯录联系人是否已经加入好友。取值：1--已加好友，2--可以加好友，3--不能加好友，4--对方等级高(不能加，也不能邀请)
     * </pre>
     */
    java.lang.String getHasLink();
    /**
     * <code>optional string hasLink = 4;</code>
     *
     * <pre>
     * 通讯录联系人是否已经加入好友。取值：1--已加好友，2--可以加好友，3--不能加好友，4--对方等级高(不能加，也不能邀请)
     * </pre>
     */
    com.google.protobuf.ByteString
        getHasLinkBytes();

    /**
     * <code>optional string headImgURL = 5;</code>
     *
     * <pre>
     * 用户图像url地址
     * </pre>
     */
    java.lang.String getHeadImgURL();
    /**
     * <code>optional string headImgURL = 5;</code>
     *
     * <pre>
     * 用户图像url地址
     * </pre>
     */
    com.google.protobuf.ByteString
        getHeadImgURLBytes();

    /**
     * <code>optional int32 levelType = 6;</code>
     *
     * <pre>
     * 用户等级(完全遵循account.proto中ELevelType的规范：0=普通用户,1=VIP用户,2=VIP+用户,3=VO用户,4=游客)	
     * </pre>
     */
    int getLevelType();
  }
  /**
   * Protobuf type {@code bbproto.PContactLinkInfo}
   */
  public  static final class PContactLinkInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:bbproto.PContactLinkInfo)
      PContactLinkInfoOrBuilder {
    // Use PContactLinkInfo.newBuilder() to construct.
    private PContactLinkInfo(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private PContactLinkInfo() {
      uuid_ = "";
      mobile_ = "";
      nickName_ = "";
      hasLink_ = "";
      headImgURL_ = "";
      levelType_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PContactLinkInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              uuid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              mobile_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();

              nickName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();

              hasLink_ = bs;
              break;
            }
            case 42: {
              com.google.protobuf.ByteString bs = input.readBytes();

              headImgURL_ = bs;
              break;
            }
            case 48: {

              levelType_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PContactLinkInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PContactLinkInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.class, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * 通讯录联系人的uuid
     * </pre>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 1;</code>
     *
     * <pre>
     * 通讯录联系人的uuid
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MOBILE_FIELD_NUMBER = 2;
    private volatile java.lang.Object mobile_;
    /**
     * <code>optional string mobile = 2;</code>
     *
     * <pre>
     * 通讯录联系人的手机号码
     * </pre>
     */
    public java.lang.String getMobile() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          mobile_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string mobile = 2;</code>
     *
     * <pre>
     * 通讯录联系人的手机号码
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMobileBytes() {
      java.lang.Object ref = mobile_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        mobile_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object nickName_;
    /**
     * <code>optional string nickName = 3;</code>
     *
     * <pre>
     * 通讯录联系人的昵称
     * </pre>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nickName = 3;</code>
     *
     * <pre>
     * 通讯录联系人的昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HASLINK_FIELD_NUMBER = 4;
    private volatile java.lang.Object hasLink_;
    /**
     * <code>optional string hasLink = 4;</code>
     *
     * <pre>
     * 通讯录联系人是否已经加入好友。取值：1--已加好友，2--可以加好友，3--不能加好友，4--对方等级高(不能加，也不能邀请)
     * </pre>
     */
    public java.lang.String getHasLink() {
      java.lang.Object ref = hasLink_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          hasLink_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string hasLink = 4;</code>
     *
     * <pre>
     * 通讯录联系人是否已经加入好友。取值：1--已加好友，2--可以加好友，3--不能加好友，4--对方等级高(不能加，也不能邀请)
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHasLinkBytes() {
      java.lang.Object ref = hasLink_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hasLink_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADIMGURL_FIELD_NUMBER = 5;
    private volatile java.lang.Object headImgURL_;
    /**
     * <code>optional string headImgURL = 5;</code>
     *
     * <pre>
     * 用户图像url地址
     * </pre>
     */
    public java.lang.String getHeadImgURL() {
      java.lang.Object ref = headImgURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          headImgURL_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string headImgURL = 5;</code>
     *
     * <pre>
     * 用户图像url地址
     * </pre>
     */
    public com.google.protobuf.ByteString
        getHeadImgURLBytes() {
      java.lang.Object ref = headImgURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headImgURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVELTYPE_FIELD_NUMBER = 6;
    private int levelType_;
    /**
     * <code>optional int32 levelType = 6;</code>
     *
     * <pre>
     * 用户等级(完全遵循account.proto中ELevelType的规范：0=普通用户,1=VIP用户,2=VIP+用户,3=VO用户,4=游客)	
     * </pre>
     */
    public int getLevelType() {
      return levelType_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUuidBytes().isEmpty()) {
        output.writeBytes(1, getUuidBytes());
      }
      if (!getMobileBytes().isEmpty()) {
        output.writeBytes(2, getMobileBytes());
      }
      if (!getNickNameBytes().isEmpty()) {
        output.writeBytes(3, getNickNameBytes());
      }
      if (!getHasLinkBytes().isEmpty()) {
        output.writeBytes(4, getHasLinkBytes());
      }
      if (!getHeadImgURLBytes().isEmpty()) {
        output.writeBytes(5, getHeadImgURLBytes());
      }
      if (levelType_ != 0) {
        output.writeInt32(6, levelType_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getUuidBytes());
      }
      if (!getMobileBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getMobileBytes());
      }
      if (!getNickNameBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getNickNameBytes());
      }
      if (!getHasLinkBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getHasLinkBytes());
      }
      if (!getHeadImgURLBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getHeadImgURLBytes());
      }
      if (levelType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, levelType_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bbproto.PContactLinkInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bbproto.PContactLinkInfo)
        com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PContactLinkInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PContactLinkInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.class, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder.class);
      }

      // Construct using com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        uuid_ = "";

        mobile_ = "";

        nickName_ = "";

        hasLink_ = "";

        headImgURL_ = "";

        levelType_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PContactLinkInfo_descriptor;
      }

      public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo getDefaultInstanceForType() {
        return com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.getDefaultInstance();
      }

      public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo build() {
        com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo buildPartial() {
        com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo result = new com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo(this);
        result.uuid_ = uuid_;
        result.mobile_ = mobile_;
        result.nickName_ = nickName_;
        result.hasLink_ = hasLink_;
        result.headImgURL_ = headImgURL_;
        result.levelType_ = levelType_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo) {
          return mergeFrom((com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo other) {
        if (other == com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (!other.getMobile().isEmpty()) {
          mobile_ = other.mobile_;
          onChanged();
        }
        if (!other.getNickName().isEmpty()) {
          nickName_ = other.nickName_;
          onChanged();
        }
        if (!other.getHasLink().isEmpty()) {
          hasLink_ = other.hasLink_;
          onChanged();
        }
        if (!other.getHeadImgURL().isEmpty()) {
          headImgURL_ = other.headImgURL_;
          onChanged();
        }
        if (other.getLevelType() != 0) {
          setLevelType(other.getLevelType());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * 通讯录联系人的uuid
       * </pre>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * 通讯录联系人的uuid
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * 通讯录联系人的uuid
       * </pre>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * 通讯录联系人的uuid
       * </pre>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 1;</code>
       *
       * <pre>
       * 通讯录联系人的uuid
       * </pre>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object mobile_ = "";
      /**
       * <code>optional string mobile = 2;</code>
       *
       * <pre>
       * 通讯录联系人的手机号码
       * </pre>
       */
      public java.lang.String getMobile() {
        java.lang.Object ref = mobile_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            mobile_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string mobile = 2;</code>
       *
       * <pre>
       * 通讯录联系人的手机号码
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMobileBytes() {
        java.lang.Object ref = mobile_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          mobile_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string mobile = 2;</code>
       *
       * <pre>
       * 通讯录联系人的手机号码
       * </pre>
       */
      public Builder setMobile(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 2;</code>
       *
       * <pre>
       * 通讯录联系人的手机号码
       * </pre>
       */
      public Builder clearMobile() {
        
        mobile_ = getDefaultInstance().getMobile();
        onChanged();
        return this;
      }
      /**
       * <code>optional string mobile = 2;</code>
       *
       * <pre>
       * 通讯录联系人的手机号码
       * </pre>
       */
      public Builder setMobileBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        mobile_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickName_ = "";
      /**
       * <code>optional string nickName = 3;</code>
       *
       * <pre>
       * 通讯录联系人的昵称
       * </pre>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickName = 3;</code>
       *
       * <pre>
       * 通讯录联系人的昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickName = 3;</code>
       *
       * <pre>
       * 通讯录联系人的昵称
       * </pre>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickName = 3;</code>
       *
       * <pre>
       * 通讯录联系人的昵称
       * </pre>
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickName = 3;</code>
       *
       * <pre>
       * 通讯录联系人的昵称
       * </pre>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object hasLink_ = "";
      /**
       * <code>optional string hasLink = 4;</code>
       *
       * <pre>
       * 通讯录联系人是否已经加入好友。取值：1--已加好友，2--可以加好友，3--不能加好友，4--对方等级高(不能加，也不能邀请)
       * </pre>
       */
      public java.lang.String getHasLink() {
        java.lang.Object ref = hasLink_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            hasLink_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string hasLink = 4;</code>
       *
       * <pre>
       * 通讯录联系人是否已经加入好友。取值：1--已加好友，2--可以加好友，3--不能加好友，4--对方等级高(不能加，也不能邀请)
       * </pre>
       */
      public com.google.protobuf.ByteString
          getHasLinkBytes() {
        java.lang.Object ref = hasLink_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          hasLink_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string hasLink = 4;</code>
       *
       * <pre>
       * 通讯录联系人是否已经加入好友。取值：1--已加好友，2--可以加好友，3--不能加好友，4--对方等级高(不能加，也不能邀请)
       * </pre>
       */
      public Builder setHasLink(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hasLink_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string hasLink = 4;</code>
       *
       * <pre>
       * 通讯录联系人是否已经加入好友。取值：1--已加好友，2--可以加好友，3--不能加好友，4--对方等级高(不能加，也不能邀请)
       * </pre>
       */
      public Builder clearHasLink() {
        
        hasLink_ = getDefaultInstance().getHasLink();
        onChanged();
        return this;
      }
      /**
       * <code>optional string hasLink = 4;</code>
       *
       * <pre>
       * 通讯录联系人是否已经加入好友。取值：1--已加好友，2--可以加好友，3--不能加好友，4--对方等级高(不能加，也不能邀请)
       * </pre>
       */
      public Builder setHasLinkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        hasLink_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object headImgURL_ = "";
      /**
       * <code>optional string headImgURL = 5;</code>
       *
       * <pre>
       * 用户图像url地址
       * </pre>
       */
      public java.lang.String getHeadImgURL() {
        java.lang.Object ref = headImgURL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            headImgURL_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string headImgURL = 5;</code>
       *
       * <pre>
       * 用户图像url地址
       * </pre>
       */
      public com.google.protobuf.ByteString
          getHeadImgURLBytes() {
        java.lang.Object ref = headImgURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headImgURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string headImgURL = 5;</code>
       *
       * <pre>
       * 用户图像url地址
       * </pre>
       */
      public Builder setHeadImgURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        headImgURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string headImgURL = 5;</code>
       *
       * <pre>
       * 用户图像url地址
       * </pre>
       */
      public Builder clearHeadImgURL() {
        
        headImgURL_ = getDefaultInstance().getHeadImgURL();
        onChanged();
        return this;
      }
      /**
       * <code>optional string headImgURL = 5;</code>
       *
       * <pre>
       * 用户图像url地址
       * </pre>
       */
      public Builder setHeadImgURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        headImgURL_ = value;
        onChanged();
        return this;
      }

      private int levelType_ ;
      /**
       * <code>optional int32 levelType = 6;</code>
       *
       * <pre>
       * 用户等级(完全遵循account.proto中ELevelType的规范：0=普通用户,1=VIP用户,2=VIP+用户,3=VO用户,4=游客)	
       * </pre>
       */
      public int getLevelType() {
        return levelType_;
      }
      /**
       * <code>optional int32 levelType = 6;</code>
       *
       * <pre>
       * 用户等级(完全遵循account.proto中ELevelType的规范：0=普通用户,1=VIP用户,2=VIP+用户,3=VO用户,4=游客)	
       * </pre>
       */
      public Builder setLevelType(int value) {
        
        levelType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 levelType = 6;</code>
       *
       * <pre>
       * 用户等级(完全遵循account.proto中ELevelType的规范：0=普通用户,1=VIP用户,2=VIP+用户,3=VO用户,4=游客)	
       * </pre>
       */
      public Builder clearLevelType() {
        
        levelType_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bbproto.PContactLinkInfo)
    }

    // @@protoc_insertion_point(class_scope:bbproto.PContactLinkInfo)
    private static final com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo();
    }

    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PContactLinkInfo> PARSER =
        new com.google.protobuf.AbstractParser<PContactLinkInfo>() {
      public PContactLinkInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PContactLinkInfo(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PContactLinkInfo> getParserForType() {
      return PARSER;
    }

    public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PContactLinkInfoListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bbproto.PContactLinkInfoList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
     */
    java.util.List<com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo> 
        getContactUsersList();
    /**
     * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
     */
    com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo getContactUsers(int index);
    /**
     * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
     */
    int getContactUsersCount();
    /**
     * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
     */
    java.util.List<? extends com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoOrBuilder> 
        getContactUsersOrBuilderList();
    /**
     * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
     */
    com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoOrBuilder getContactUsersOrBuilder(
        int index);

    /**
     * <code>optional string totalCount = 2;</code>
     *
     * <pre>
     * 总记录数
     * </pre>
     */
    java.lang.String getTotalCount();
    /**
     * <code>optional string totalCount = 2;</code>
     *
     * <pre>
     * 总记录数
     * </pre>
     */
    com.google.protobuf.ByteString
        getTotalCountBytes();
  }
  /**
   * Protobuf type {@code bbproto.PContactLinkInfoList}
   *
   * <pre>
   * 下载通讯录好友关系
   * </pre>
   */
  public  static final class PContactLinkInfoList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:bbproto.PContactLinkInfoList)
      PContactLinkInfoListOrBuilder {
    // Use PContactLinkInfoList.newBuilder() to construct.
    private PContactLinkInfoList(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private PContactLinkInfoList() {
      contactUsers_ = java.util.Collections.emptyList();
      totalCount_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PContactLinkInfoList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                contactUsers_ = new java.util.ArrayList<com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo>();
                mutable_bitField0_ |= 0x00000001;
              }
              contactUsers_.add(input.readMessage(com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              totalCount_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          contactUsers_ = java.util.Collections.unmodifiableList(contactUsers_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PContactLinkInfoList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PContactLinkInfoList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList.class, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList.Builder.class);
    }

    private int bitField0_;
    public static final int CONTACTUSERS_FIELD_NUMBER = 1;
    private java.util.List<com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo> contactUsers_;
    /**
     * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
     */
    public java.util.List<com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo> getContactUsersList() {
      return contactUsers_;
    }
    /**
     * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
     */
    public java.util.List<? extends com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoOrBuilder> 
        getContactUsersOrBuilderList() {
      return contactUsers_;
    }
    /**
     * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
     */
    public int getContactUsersCount() {
      return contactUsers_.size();
    }
    /**
     * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
     */
    public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo getContactUsers(int index) {
      return contactUsers_.get(index);
    }
    /**
     * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
     */
    public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoOrBuilder getContactUsersOrBuilder(
        int index) {
      return contactUsers_.get(index);
    }

    public static final int TOTALCOUNT_FIELD_NUMBER = 2;
    private volatile java.lang.Object totalCount_;
    /**
     * <code>optional string totalCount = 2;</code>
     *
     * <pre>
     * 总记录数
     * </pre>
     */
    public java.lang.String getTotalCount() {
      java.lang.Object ref = totalCount_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          totalCount_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string totalCount = 2;</code>
     *
     * <pre>
     * 总记录数
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTotalCountBytes() {
      java.lang.Object ref = totalCount_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        totalCount_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < contactUsers_.size(); i++) {
        output.writeMessage(1, contactUsers_.get(i));
      }
      if (!getTotalCountBytes().isEmpty()) {
        output.writeBytes(2, getTotalCountBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < contactUsers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, contactUsers_.get(i));
      }
      if (!getTotalCountBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getTotalCountBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bbproto.PContactLinkInfoList}
     *
     * <pre>
     * 下载通讯录好友关系
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bbproto.PContactLinkInfoList)
        com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PContactLinkInfoList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PContactLinkInfoList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList.class, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList.Builder.class);
      }

      // Construct using com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContactUsersFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (contactUsersBuilder_ == null) {
          contactUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          contactUsersBuilder_.clear();
        }
        totalCount_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PContactLinkInfoList_descriptor;
      }

      public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList getDefaultInstanceForType() {
        return com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList.getDefaultInstance();
      }

      public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList build() {
        com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList buildPartial() {
        com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList result = new com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (contactUsersBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            contactUsers_ = java.util.Collections.unmodifiableList(contactUsers_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.contactUsers_ = contactUsers_;
        } else {
          result.contactUsers_ = contactUsersBuilder_.build();
        }
        result.totalCount_ = totalCount_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList) {
          return mergeFrom((com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList other) {
        if (other == com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList.getDefaultInstance()) return this;
        if (contactUsersBuilder_ == null) {
          if (!other.contactUsers_.isEmpty()) {
            if (contactUsers_.isEmpty()) {
              contactUsers_ = other.contactUsers_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContactUsersIsMutable();
              contactUsers_.addAll(other.contactUsers_);
            }
            onChanged();
          }
        } else {
          if (!other.contactUsers_.isEmpty()) {
            if (contactUsersBuilder_.isEmpty()) {
              contactUsersBuilder_.dispose();
              contactUsersBuilder_ = null;
              contactUsers_ = other.contactUsers_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contactUsersBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getContactUsersFieldBuilder() : null;
            } else {
              contactUsersBuilder_.addAllMessages(other.contactUsers_);
            }
          }
        }
        if (!other.getTotalCount().isEmpty()) {
          totalCount_ = other.totalCount_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo> contactUsers_ =
        java.util.Collections.emptyList();
      private void ensureContactUsersIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          contactUsers_ = new java.util.ArrayList<com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo>(contactUsers_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoOrBuilder> contactUsersBuilder_;

      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public java.util.List<com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo> getContactUsersList() {
        if (contactUsersBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contactUsers_);
        } else {
          return contactUsersBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public int getContactUsersCount() {
        if (contactUsersBuilder_ == null) {
          return contactUsers_.size();
        } else {
          return contactUsersBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo getContactUsers(int index) {
        if (contactUsersBuilder_ == null) {
          return contactUsers_.get(index);
        } else {
          return contactUsersBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public Builder setContactUsers(
          int index, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo value) {
        if (contactUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactUsersIsMutable();
          contactUsers_.set(index, value);
          onChanged();
        } else {
          contactUsersBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public Builder setContactUsers(
          int index, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder builderForValue) {
        if (contactUsersBuilder_ == null) {
          ensureContactUsersIsMutable();
          contactUsers_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactUsersBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public Builder addContactUsers(com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo value) {
        if (contactUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactUsersIsMutable();
          contactUsers_.add(value);
          onChanged();
        } else {
          contactUsersBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public Builder addContactUsers(
          int index, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo value) {
        if (contactUsersBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactUsersIsMutable();
          contactUsers_.add(index, value);
          onChanged();
        } else {
          contactUsersBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public Builder addContactUsers(
          com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder builderForValue) {
        if (contactUsersBuilder_ == null) {
          ensureContactUsersIsMutable();
          contactUsers_.add(builderForValue.build());
          onChanged();
        } else {
          contactUsersBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public Builder addContactUsers(
          int index, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder builderForValue) {
        if (contactUsersBuilder_ == null) {
          ensureContactUsersIsMutable();
          contactUsers_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactUsersBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public Builder addAllContactUsers(
          java.lang.Iterable<? extends com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo> values) {
        if (contactUsersBuilder_ == null) {
          ensureContactUsersIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contactUsers_);
          onChanged();
        } else {
          contactUsersBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public Builder clearContactUsers() {
        if (contactUsersBuilder_ == null) {
          contactUsers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contactUsersBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public Builder removeContactUsers(int index) {
        if (contactUsersBuilder_ == null) {
          ensureContactUsersIsMutable();
          contactUsers_.remove(index);
          onChanged();
        } else {
          contactUsersBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder getContactUsersBuilder(
          int index) {
        return getContactUsersFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoOrBuilder getContactUsersOrBuilder(
          int index) {
        if (contactUsersBuilder_ == null) {
          return contactUsers_.get(index);  } else {
          return contactUsersBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public java.util.List<? extends com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoOrBuilder> 
           getContactUsersOrBuilderList() {
        if (contactUsersBuilder_ != null) {
          return contactUsersBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contactUsers_);
        }
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder addContactUsersBuilder() {
        return getContactUsersFieldBuilder().addBuilder(
            com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder addContactUsersBuilder(
          int index) {
        return getContactUsersFieldBuilder().addBuilder(
            index, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .bbproto.PContactLinkInfo ContactUsers = 1;</code>
       */
      public java.util.List<com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder> 
           getContactUsersBuilderList() {
        return getContactUsersFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoOrBuilder> 
          getContactUsersFieldBuilder() {
        if (contactUsersBuilder_ == null) {
          contactUsersBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfo.Builder, com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoOrBuilder>(
                  contactUsers_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          contactUsers_ = null;
        }
        return contactUsersBuilder_;
      }

      private java.lang.Object totalCount_ = "";
      /**
       * <code>optional string totalCount = 2;</code>
       *
       * <pre>
       * 总记录数
       * </pre>
       */
      public java.lang.String getTotalCount() {
        java.lang.Object ref = totalCount_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            totalCount_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string totalCount = 2;</code>
       *
       * <pre>
       * 总记录数
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTotalCountBytes() {
        java.lang.Object ref = totalCount_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          totalCount_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string totalCount = 2;</code>
       *
       * <pre>
       * 总记录数
       * </pre>
       */
      public Builder setTotalCount(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        totalCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string totalCount = 2;</code>
       *
       * <pre>
       * 总记录数
       * </pre>
       */
      public Builder clearTotalCount() {
        
        totalCount_ = getDefaultInstance().getTotalCount();
        onChanged();
        return this;
      }
      /**
       * <code>optional string totalCount = 2;</code>
       *
       * <pre>
       * 总记录数
       * </pre>
       */
      public Builder setTotalCountBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        totalCount_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bbproto.PContactLinkInfoList)
    }

    // @@protoc_insertion_point(class_scope:bbproto.PContactLinkInfoList)
    private static final com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList();
    }

    public static com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PContactLinkInfoList> PARSER =
        new com.google.protobuf.AbstractParser<PContactLinkInfoList>() {
      public PContactLinkInfoList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PContactLinkInfoList(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PContactLinkInfoList> getParserForType() {
      return PARSER;
    }

    public com.blemobi.sep.probuf.ContactProtos.PContactLinkInfoList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PLastModifyInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bbproto.PLastModifyInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string devSerial = 1;</code>
     *
     * <pre>
     * 设备串行号
     * </pre>
     */
    java.lang.String getDevSerial();
    /**
     * <code>optional string devSerial = 1;</code>
     *
     * <pre>
     * 设备串行号
     * </pre>
     */
    com.google.protobuf.ByteString
        getDevSerialBytes();

    /**
     * <code>optional string modifyTime = 2;</code>
     *
     * <pre>
     * 最后时间
     * </pre>
     */
    java.lang.String getModifyTime();
    /**
     * <code>optional string modifyTime = 2;</code>
     *
     * <pre>
     * 最后时间
     * </pre>
     */
    com.google.protobuf.ByteString
        getModifyTimeBytes();
  }
  /**
   * Protobuf type {@code bbproto.PLastModifyInfo}
   *
   * <pre>
   * 访问设备的最后修改时间
   * </pre>
   */
  public  static final class PLastModifyInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:bbproto.PLastModifyInfo)
      PLastModifyInfoOrBuilder {
    // Use PLastModifyInfo.newBuilder() to construct.
    private PLastModifyInfo(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private PLastModifyInfo() {
      devSerial_ = "";
      modifyTime_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PLastModifyInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              devSerial_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              modifyTime_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PLastModifyInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PLastModifyInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo.class, com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo.Builder.class);
    }

    public static final int DEVSERIAL_FIELD_NUMBER = 1;
    private volatile java.lang.Object devSerial_;
    /**
     * <code>optional string devSerial = 1;</code>
     *
     * <pre>
     * 设备串行号
     * </pre>
     */
    public java.lang.String getDevSerial() {
      java.lang.Object ref = devSerial_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          devSerial_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string devSerial = 1;</code>
     *
     * <pre>
     * 设备串行号
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDevSerialBytes() {
      java.lang.Object ref = devSerial_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        devSerial_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MODIFYTIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object modifyTime_;
    /**
     * <code>optional string modifyTime = 2;</code>
     *
     * <pre>
     * 最后时间
     * </pre>
     */
    public java.lang.String getModifyTime() {
      java.lang.Object ref = modifyTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          modifyTime_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string modifyTime = 2;</code>
     *
     * <pre>
     * 最后时间
     * </pre>
     */
    public com.google.protobuf.ByteString
        getModifyTimeBytes() {
      java.lang.Object ref = modifyTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modifyTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getDevSerialBytes().isEmpty()) {
        output.writeBytes(1, getDevSerialBytes());
      }
      if (!getModifyTimeBytes().isEmpty()) {
        output.writeBytes(2, getModifyTimeBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getDevSerialBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getDevSerialBytes());
      }
      if (!getModifyTimeBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getModifyTimeBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bbproto.PLastModifyInfo}
     *
     * <pre>
     * 访问设备的最后修改时间
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bbproto.PLastModifyInfo)
        com.blemobi.sep.probuf.ContactProtos.PLastModifyInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PLastModifyInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PLastModifyInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo.class, com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo.Builder.class);
      }

      // Construct using com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        devSerial_ = "";

        modifyTime_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blemobi.sep.probuf.ContactProtos.internal_static_bbproto_PLastModifyInfo_descriptor;
      }

      public com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo getDefaultInstanceForType() {
        return com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo.getDefaultInstance();
      }

      public com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo build() {
        com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo buildPartial() {
        com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo result = new com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo(this);
        result.devSerial_ = devSerial_;
        result.modifyTime_ = modifyTime_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo) {
          return mergeFrom((com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo other) {
        if (other == com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo.getDefaultInstance()) return this;
        if (!other.getDevSerial().isEmpty()) {
          devSerial_ = other.devSerial_;
          onChanged();
        }
        if (!other.getModifyTime().isEmpty()) {
          modifyTime_ = other.modifyTime_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object devSerial_ = "";
      /**
       * <code>optional string devSerial = 1;</code>
       *
       * <pre>
       * 设备串行号
       * </pre>
       */
      public java.lang.String getDevSerial() {
        java.lang.Object ref = devSerial_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            devSerial_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string devSerial = 1;</code>
       *
       * <pre>
       * 设备串行号
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDevSerialBytes() {
        java.lang.Object ref = devSerial_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          devSerial_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string devSerial = 1;</code>
       *
       * <pre>
       * 设备串行号
       * </pre>
       */
      public Builder setDevSerial(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        devSerial_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string devSerial = 1;</code>
       *
       * <pre>
       * 设备串行号
       * </pre>
       */
      public Builder clearDevSerial() {
        
        devSerial_ = getDefaultInstance().getDevSerial();
        onChanged();
        return this;
      }
      /**
       * <code>optional string devSerial = 1;</code>
       *
       * <pre>
       * 设备串行号
       * </pre>
       */
      public Builder setDevSerialBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        devSerial_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object modifyTime_ = "";
      /**
       * <code>optional string modifyTime = 2;</code>
       *
       * <pre>
       * 最后时间
       * </pre>
       */
      public java.lang.String getModifyTime() {
        java.lang.Object ref = modifyTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            modifyTime_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string modifyTime = 2;</code>
       *
       * <pre>
       * 最后时间
       * </pre>
       */
      public com.google.protobuf.ByteString
          getModifyTimeBytes() {
        java.lang.Object ref = modifyTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          modifyTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string modifyTime = 2;</code>
       *
       * <pre>
       * 最后时间
       * </pre>
       */
      public Builder setModifyTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        modifyTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string modifyTime = 2;</code>
       *
       * <pre>
       * 最后时间
       * </pre>
       */
      public Builder clearModifyTime() {
        
        modifyTime_ = getDefaultInstance().getModifyTime();
        onChanged();
        return this;
      }
      /**
       * <code>optional string modifyTime = 2;</code>
       *
       * <pre>
       * 最后时间
       * </pre>
       */
      public Builder setModifyTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        modifyTime_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bbproto.PLastModifyInfo)
    }

    // @@protoc_insertion_point(class_scope:bbproto.PLastModifyInfo)
    private static final com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo();
    }

    public static com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PLastModifyInfo> PARSER =
        new com.google.protobuf.AbstractParser<PLastModifyInfo>() {
      public PLastModifyInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PLastModifyInfo(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PLastModifyInfo> getParserForType() {
      return PARSER;
    }

    public com.blemobi.sep.probuf.ContactProtos.PLastModifyInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bbproto_PContactLinkInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bbproto_PContactLinkInfo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bbproto_PContactLinkInfoList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bbproto_PContactLinkInfoList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bbproto_PLastModifyInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bbproto_PLastModifyInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcontact.proto\022\007bbproto\"z\n\020PContactLink" +
      "Info\022\014\n\004uuid\030\001 \001(\t\022\016\n\006mobile\030\002 \001(\t\022\020\n\010ni" +
      "ckName\030\003 \001(\t\022\017\n\007hasLink\030\004 \001(\t\022\022\n\nheadImg" +
      "URL\030\005 \001(\t\022\021\n\tlevelType\030\006 \001(\005\"[\n\024PContact" +
      "LinkInfoList\022/\n\014ContactUsers\030\001 \003(\0132\031.bbp" +
      "roto.PContactLinkInfo\022\022\n\ntotalCount\030\002 \001(" +
      "\t\"8\n\017PLastModifyInfo\022\021\n\tdevSerial\030\001 \001(\t\022" +
      "\022\n\nmodifyTime\030\002 \001(\tB\'\n\026com.blemobi.sep.p" +
      "robufB\rContactProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_bbproto_PContactLinkInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bbproto_PContactLinkInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bbproto_PContactLinkInfo_descriptor,
        new java.lang.String[] { "Uuid", "Mobile", "NickName", "HasLink", "HeadImgURL", "LevelType", });
    internal_static_bbproto_PContactLinkInfoList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bbproto_PContactLinkInfoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bbproto_PContactLinkInfoList_descriptor,
        new java.lang.String[] { "ContactUsers", "TotalCount", });
    internal_static_bbproto_PLastModifyInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_bbproto_PLastModifyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bbproto_PLastModifyInfo_descriptor,
        new java.lang.String[] { "DevSerial", "ModifyTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
