// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: server-server/friend_group.proto

package com.blemobi.sep.probuf;

public final class FriendGroupProtos {
  private FriendGroupProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PGroupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:common.PGroup)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string title = 1;</code>
     *
     * <pre>
     * 群名称
     * </pre>
     */
    java.lang.String getTitle();
    /**
     * <code>optional string title = 1;</code>
     *
     * <pre>
     * 群名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>optional string icon = 2;</code>
     *
     * <pre>
     * 群头像url  
     * </pre>
     */
    java.lang.String getIcon();
    /**
     * <code>optional string icon = 2;</code>
     *
     * <pre>
     * 群头像url  
     * </pre>
     */
    com.google.protobuf.ByteString
        getIconBytes();

    /**
     * <code>optional int32 superGroup = 3;</code>
     *
     * <pre>
     * 0非大群，1大群
     * </pre>
     */
    int getSuperGroup();

    /**
     * <code>optional int32 memberLimit = 4;</code>
     *
     * <pre>
     * 最大人数
     * </pre>
     */
    int getMemberLimit();

    /**
     * <code>repeated int64 members = 5;</code>
     *
     * <pre>
     * 群成员列表openId
     * </pre>
     */
    java.util.List<java.lang.Long> getMembersList();
    /**
     * <code>repeated int64 members = 5;</code>
     *
     * <pre>
     * 群成员列表openId
     * </pre>
     */
    int getMembersCount();
    /**
     * <code>repeated int64 members = 5;</code>
     *
     * <pre>
     * 群成员列表openId
     * </pre>
     */
    long getMembers(int index);
  }
  /**
   * Protobuf type {@code common.PGroup}
   */
  public  static final class PGroup extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:common.PGroup)
      PGroupOrBuilder {
    // Use PGroup.newBuilder() to construct.
    private PGroup(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private PGroup() {
      title_ = "";
      icon_ = "";
      superGroup_ = 0;
      memberLimit_ = 0;
      members_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PGroup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();

              title_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();

              icon_ = bs;
              break;
            }
            case 24: {

              superGroup_ = input.readInt32();
              break;
            }
            case 32: {

              memberLimit_ = input.readInt32();
              break;
            }
            case 40: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                members_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              members_.add(input.readInt64());
              break;
            }
            case 42: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
                members_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000010;
              }
              while (input.getBytesUntilLimit() > 0) {
                members_.add(input.readInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          members_ = java.util.Collections.unmodifiableList(members_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blemobi.sep.probuf.FriendGroupProtos.internal_static_common_PGroup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blemobi.sep.probuf.FriendGroupProtos.internal_static_common_PGroup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blemobi.sep.probuf.FriendGroupProtos.PGroup.class, com.blemobi.sep.probuf.FriendGroupProtos.PGroup.Builder.class);
    }

    private int bitField0_;
    public static final int TITLE_FIELD_NUMBER = 1;
    private volatile java.lang.Object title_;
    /**
     * <code>optional string title = 1;</code>
     *
     * <pre>
     * 群名称
     * </pre>
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          title_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string title = 1;</code>
     *
     * <pre>
     * 群名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ICON_FIELD_NUMBER = 2;
    private volatile java.lang.Object icon_;
    /**
     * <code>optional string icon = 2;</code>
     *
     * <pre>
     * 群头像url  
     * </pre>
     */
    public java.lang.String getIcon() {
      java.lang.Object ref = icon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          icon_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string icon = 2;</code>
     *
     * <pre>
     * 群头像url  
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIconBytes() {
      java.lang.Object ref = icon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUPERGROUP_FIELD_NUMBER = 3;
    private int superGroup_;
    /**
     * <code>optional int32 superGroup = 3;</code>
     *
     * <pre>
     * 0非大群，1大群
     * </pre>
     */
    public int getSuperGroup() {
      return superGroup_;
    }

    public static final int MEMBERLIMIT_FIELD_NUMBER = 4;
    private int memberLimit_;
    /**
     * <code>optional int32 memberLimit = 4;</code>
     *
     * <pre>
     * 最大人数
     * </pre>
     */
    public int getMemberLimit() {
      return memberLimit_;
    }

    public static final int MEMBERS_FIELD_NUMBER = 5;
    private java.util.List<java.lang.Long> members_;
    /**
     * <code>repeated int64 members = 5;</code>
     *
     * <pre>
     * 群成员列表openId
     * </pre>
     */
    public java.util.List<java.lang.Long>
        getMembersList() {
      return members_;
    }
    /**
     * <code>repeated int64 members = 5;</code>
     *
     * <pre>
     * 群成员列表openId
     * </pre>
     */
    public int getMembersCount() {
      return members_.size();
    }
    /**
     * <code>repeated int64 members = 5;</code>
     *
     * <pre>
     * 群成员列表openId
     * </pre>
     */
    public long getMembers(int index) {
      return members_.get(index);
    }
    private int membersMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getTitleBytes().isEmpty()) {
        output.writeBytes(1, getTitleBytes());
      }
      if (!getIconBytes().isEmpty()) {
        output.writeBytes(2, getIconBytes());
      }
      if (superGroup_ != 0) {
        output.writeInt32(3, superGroup_);
      }
      if (memberLimit_ != 0) {
        output.writeInt32(4, memberLimit_);
      }
      if (getMembersList().size() > 0) {
        output.writeRawVarint32(42);
        output.writeRawVarint32(membersMemoizedSerializedSize);
      }
      for (int i = 0; i < members_.size(); i++) {
        output.writeInt64NoTag(members_.get(i));
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTitleBytes());
      }
      if (!getIconBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIconBytes());
      }
      if (superGroup_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, superGroup_);
      }
      if (memberLimit_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, memberLimit_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < members_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt64SizeNoTag(members_.get(i));
        }
        size += dataSize;
        if (!getMembersList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        membersMemoizedSerializedSize = dataSize;
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.blemobi.sep.probuf.FriendGroupProtos.PGroup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.FriendGroupProtos.PGroup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.FriendGroupProtos.PGroup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.FriendGroupProtos.PGroup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.FriendGroupProtos.PGroup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.FriendGroupProtos.PGroup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.FriendGroupProtos.PGroup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.blemobi.sep.probuf.FriendGroupProtos.PGroup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.FriendGroupProtos.PGroup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.FriendGroupProtos.PGroup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blemobi.sep.probuf.FriendGroupProtos.PGroup prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code common.PGroup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:common.PGroup)
        com.blemobi.sep.probuf.FriendGroupProtos.PGroupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blemobi.sep.probuf.FriendGroupProtos.internal_static_common_PGroup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blemobi.sep.probuf.FriendGroupProtos.internal_static_common_PGroup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blemobi.sep.probuf.FriendGroupProtos.PGroup.class, com.blemobi.sep.probuf.FriendGroupProtos.PGroup.Builder.class);
      }

      // Construct using com.blemobi.demo.probuf.FriendGroupProtos.PGroup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        title_ = "";

        icon_ = "";

        superGroup_ = 0;

        memberLimit_ = 0;

        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blemobi.sep.probuf.FriendGroupProtos.internal_static_common_PGroup_descriptor;
      }

      public com.blemobi.sep.probuf.FriendGroupProtos.PGroup getDefaultInstanceForType() {
        return com.blemobi.sep.probuf.FriendGroupProtos.PGroup.getDefaultInstance();
      }

      public com.blemobi.sep.probuf.FriendGroupProtos.PGroup build() {
        com.blemobi.sep.probuf.FriendGroupProtos.PGroup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blemobi.sep.probuf.FriendGroupProtos.PGroup buildPartial() {
        com.blemobi.sep.probuf.FriendGroupProtos.PGroup result = new com.blemobi.sep.probuf.FriendGroupProtos.PGroup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.title_ = title_;
        result.icon_ = icon_;
        result.superGroup_ = superGroup_;
        result.memberLimit_ = memberLimit_;
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          members_ = java.util.Collections.unmodifiableList(members_);
          bitField0_ = (bitField0_ & ~0x00000010);
        }
        result.members_ = members_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blemobi.sep.probuf.FriendGroupProtos.PGroup) {
          return mergeFrom((com.blemobi.sep.probuf.FriendGroupProtos.PGroup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blemobi.sep.probuf.FriendGroupProtos.PGroup other) {
        if (other == com.blemobi.sep.probuf.FriendGroupProtos.PGroup.getDefaultInstance()) return this;
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getIcon().isEmpty()) {
          icon_ = other.icon_;
          onChanged();
        }
        if (other.getSuperGroup() != 0) {
          setSuperGroup(other.getSuperGroup());
        }
        if (other.getMemberLimit() != 0) {
          setMemberLimit(other.getMemberLimit());
        }
        if (!other.members_.isEmpty()) {
          if (members_.isEmpty()) {
            members_ = other.members_;
            bitField0_ = (bitField0_ & ~0x00000010);
          } else {
            ensureMembersIsMutable();
            members_.addAll(other.members_);
          }
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blemobi.sep.probuf.FriendGroupProtos.PGroup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blemobi.sep.probuf.FriendGroupProtos.PGroup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object title_ = "";
      /**
       * <code>optional string title = 1;</code>
       *
       * <pre>
       * 群名称
       * </pre>
       */
      public java.lang.String getTitle() {
        java.lang.Object ref = title_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            title_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string title = 1;</code>
       *
       * <pre>
       * 群名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        java.lang.Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string title = 1;</code>
       *
       * <pre>
       * 群名称
       * </pre>
       */
      public Builder setTitle(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 1;</code>
       *
       * <pre>
       * 群名称
       * </pre>
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>optional string title = 1;</code>
       *
       * <pre>
       * 群名称
       * </pre>
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object icon_ = "";
      /**
       * <code>optional string icon = 2;</code>
       *
       * <pre>
       * 群头像url  
       * </pre>
       */
      public java.lang.String getIcon() {
        java.lang.Object ref = icon_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            icon_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string icon = 2;</code>
       *
       * <pre>
       * 群头像url  
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIconBytes() {
        java.lang.Object ref = icon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          icon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string icon = 2;</code>
       *
       * <pre>
       * 群头像url  
       * </pre>
       */
      public Builder setIcon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        icon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string icon = 2;</code>
       *
       * <pre>
       * 群头像url  
       * </pre>
       */
      public Builder clearIcon() {
        
        icon_ = getDefaultInstance().getIcon();
        onChanged();
        return this;
      }
      /**
       * <code>optional string icon = 2;</code>
       *
       * <pre>
       * 群头像url  
       * </pre>
       */
      public Builder setIconBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        icon_ = value;
        onChanged();
        return this;
      }

      private int superGroup_ ;
      /**
       * <code>optional int32 superGroup = 3;</code>
       *
       * <pre>
       * 0非大群，1大群
       * </pre>
       */
      public int getSuperGroup() {
        return superGroup_;
      }
      /**
       * <code>optional int32 superGroup = 3;</code>
       *
       * <pre>
       * 0非大群，1大群
       * </pre>
       */
      public Builder setSuperGroup(int value) {
        
        superGroup_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 superGroup = 3;</code>
       *
       * <pre>
       * 0非大群，1大群
       * </pre>
       */
      public Builder clearSuperGroup() {
        
        superGroup_ = 0;
        onChanged();
        return this;
      }

      private int memberLimit_ ;
      /**
       * <code>optional int32 memberLimit = 4;</code>
       *
       * <pre>
       * 最大人数
       * </pre>
       */
      public int getMemberLimit() {
        return memberLimit_;
      }
      /**
       * <code>optional int32 memberLimit = 4;</code>
       *
       * <pre>
       * 最大人数
       * </pre>
       */
      public Builder setMemberLimit(int value) {
        
        memberLimit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 memberLimit = 4;</code>
       *
       * <pre>
       * 最大人数
       * </pre>
       */
      public Builder clearMemberLimit() {
        
        memberLimit_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Long> members_ = java.util.Collections.emptyList();
      private void ensureMembersIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          members_ = new java.util.ArrayList<java.lang.Long>(members_);
          bitField0_ |= 0x00000010;
         }
      }
      /**
       * <code>repeated int64 members = 5;</code>
       *
       * <pre>
       * 群成员列表openId
       * </pre>
       */
      public java.util.List<java.lang.Long>
          getMembersList() {
        return java.util.Collections.unmodifiableList(members_);
      }
      /**
       * <code>repeated int64 members = 5;</code>
       *
       * <pre>
       * 群成员列表openId
       * </pre>
       */
      public int getMembersCount() {
        return members_.size();
      }
      /**
       * <code>repeated int64 members = 5;</code>
       *
       * <pre>
       * 群成员列表openId
       * </pre>
       */
      public long getMembers(int index) {
        return members_.get(index);
      }
      /**
       * <code>repeated int64 members = 5;</code>
       *
       * <pre>
       * 群成员列表openId
       * </pre>
       */
      public Builder setMembers(
          int index, long value) {
        ensureMembersIsMutable();
        members_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 members = 5;</code>
       *
       * <pre>
       * 群成员列表openId
       * </pre>
       */
      public Builder addMembers(long value) {
        ensureMembersIsMutable();
        members_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 members = 5;</code>
       *
       * <pre>
       * 群成员列表openId
       * </pre>
       */
      public Builder addAllMembers(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureMembersIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, members_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated int64 members = 5;</code>
       *
       * <pre>
       * 群成员列表openId
       * </pre>
       */
      public Builder clearMembers() {
        members_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:common.PGroup)
    }

    // @@protoc_insertion_point(class_scope:common.PGroup)
    private static final com.blemobi.sep.probuf.FriendGroupProtos.PGroup DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blemobi.sep.probuf.FriendGroupProtos.PGroup();
    }

    public static com.blemobi.sep.probuf.FriendGroupProtos.PGroup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PGroup> PARSER =
        new com.google.protobuf.AbstractParser<PGroup>() {
      public PGroup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PGroup(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PGroup> getParserForType() {
      return PARSER;
    }

    public com.blemobi.sep.probuf.FriendGroupProtos.PGroup getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_common_PGroup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_PGroup_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n server-server/friend_group.proto\022\006comm" +
      "on\"_\n\006PGroup\022\r\n\005title\030\001 \001(\t\022\014\n\004icon\030\002 \001(" +
      "\t\022\022\n\nsuperGroup\030\003 \001(\005\022\023\n\013memberLimit\030\004 \001" +
      "(\005\022\017\n\007members\030\005 \003(\003B,\n\027com.blemobi.demo." +
      "probufB\021FriendGroupProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_common_PGroup_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_common_PGroup_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_PGroup_descriptor,
        new java.lang.String[] { "Title", "Icon", "SuperGroup", "MemberLimit", "Members", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
