// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.blemobi.sep.probuf;

public final class LoginProtos {
  private LoginProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PLoginOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bbproto.PLogin)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bool forceBindPhone = 4;</code>
     *
     * <pre>
     * 用户是否需要强制绑定手机号码，如果是，则需要绑定手机号码
     * </pre>
     */
    boolean getForceBindPhone();

    /**
     * <code>optional bool newUser = 5;</code>
     *
     * <pre>
     * 是否新注册用户标识，true为新用户，false为老用户
     * </pre>
     */
    boolean getNewUser();

    /**
     * <code>optional string uuid = 6;</code>
     *
     * <pre>
     * 用户ID
     * </pre>
     */
    java.lang.String getUuid();
    /**
     * <code>optional string uuid = 6;</code>
     *
     * <pre>
     * 用户ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>optional string token = 7;</code>
     *
     * <pre>
     * 统一访问令牌
     * </pre>
     */
    java.lang.String getToken();
    /**
     * <code>optional string token = 7;</code>
     *
     * <pre>
     * 统一访问令牌
     * </pre>
     */
    com.google.protobuf.ByteString
        getTokenBytes();

    /**
     * <code>optional string nickname = 8;</code>
     *
     * <pre>
     * 用户昵称
     * </pre>
     */
    java.lang.String getNickname();
    /**
     * <code>optional string nickname = 8;</code>
     *
     * <pre>
     * 用户昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getNicknameBytes();

    /**
     * <code>optional string imgURL = 9;</code>
     *
     * <pre>
     * 用户头像URL
     * </pre>
     */
    java.lang.String getImgURL();
    /**
     * <code>optional string imgURL = 9;</code>
     *
     * <pre>
     * 用户头像URL
     * </pre>
     */
    com.google.protobuf.ByteString
        getImgURLBytes();

    /**
     * <code>optional string username = 10;</code>
     *
     * <pre>
     * 用户名称
     * </pre>
     */
    java.lang.String getUsername();
    /**
     * <code>optional string username = 10;</code>
     *
     * <pre>
     * 用户名称
     * </pre>
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
     *
     * <pre>
     * 会员等级信息
     * </pre>
     */
    boolean hasLevelInfo();
    /**
     * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
     *
     * <pre>
     * 会员等级信息
     * </pre>
     */
    com.blemobi.sep.probuf.AccountProtos.PLevelInfo getLevelInfo();
    /**
     * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
     *
     * <pre>
     * 会员等级信息
     * </pre>
     */
    com.blemobi.sep.probuf.AccountProtos.PLevelInfoOrBuilder getLevelInfoOrBuilder();
  }
  /**
   * Protobuf type {@code bbproto.PLogin}
   */
  public  static final class PLogin extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:bbproto.PLogin)
      PLoginOrBuilder {
    // Use PLogin.newBuilder() to construct.
    private PLogin(com.google.protobuf.GeneratedMessage.Builder builder) {
      super(builder);
    }
    private PLogin() {
      forceBindPhone_ = false;
      newUser_ = false;
      uuid_ = "";
      token_ = "";
      nickname_ = "";
      imgURL_ = "";
      username_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PLogin(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 32: {

              forceBindPhone_ = input.readBool();
              break;
            }
            case 40: {

              newUser_ = input.readBool();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();

              uuid_ = bs;
              break;
            }
            case 58: {
              com.google.protobuf.ByteString bs = input.readBytes();

              token_ = bs;
              break;
            }
            case 66: {
              com.google.protobuf.ByteString bs = input.readBytes();

              nickname_ = bs;
              break;
            }
            case 74: {
              com.google.protobuf.ByteString bs = input.readBytes();

              imgURL_ = bs;
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();

              username_ = bs;
              break;
            }
            case 98: {
              com.blemobi.sep.probuf.AccountProtos.PLevelInfo.Builder subBuilder = null;
              if (levelInfo_ != null) {
                subBuilder = levelInfo_.toBuilder();
              }
              levelInfo_ = input.readMessage(com.blemobi.sep.probuf.AccountProtos.PLevelInfo.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(levelInfo_);
                levelInfo_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blemobi.sep.probuf.LoginProtos.internal_static_bbproto_PLogin_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blemobi.sep.probuf.LoginProtos.internal_static_bbproto_PLogin_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blemobi.sep.probuf.LoginProtos.PLogin.class, com.blemobi.sep.probuf.LoginProtos.PLogin.Builder.class);
    }

    public static final int FORCEBINDPHONE_FIELD_NUMBER = 4;
    private boolean forceBindPhone_;
    /**
     * <code>optional bool forceBindPhone = 4;</code>
     *
     * <pre>
     * 用户是否需要强制绑定手机号码，如果是，则需要绑定手机号码
     * </pre>
     */
    public boolean getForceBindPhone() {
      return forceBindPhone_;
    }

    public static final int NEWUSER_FIELD_NUMBER = 5;
    private boolean newUser_;
    /**
     * <code>optional bool newUser = 5;</code>
     *
     * <pre>
     * 是否新注册用户标识，true为新用户，false为老用户
     * </pre>
     */
    public boolean getNewUser() {
      return newUser_;
    }

    public static final int UUID_FIELD_NUMBER = 6;
    private volatile java.lang.Object uuid_;
    /**
     * <code>optional string uuid = 6;</code>
     *
     * <pre>
     * 用户ID
     * </pre>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string uuid = 6;</code>
     *
     * <pre>
     * 用户ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TOKEN_FIELD_NUMBER = 7;
    private volatile java.lang.Object token_;
    /**
     * <code>optional string token = 7;</code>
     *
     * <pre>
     * 统一访问令牌
     * </pre>
     */
    public java.lang.String getToken() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          token_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string token = 7;</code>
     *
     * <pre>
     * 统一访问令牌
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTokenBytes() {
      java.lang.Object ref = token_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        token_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 8;
    private volatile java.lang.Object nickname_;
    /**
     * <code>optional string nickname = 8;</code>
     *
     * <pre>
     * 用户昵称
     * </pre>
     */
    public java.lang.String getNickname() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          nickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string nickname = 8;</code>
     *
     * <pre>
     * 用户昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNicknameBytes() {
      java.lang.Object ref = nickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMGURL_FIELD_NUMBER = 9;
    private volatile java.lang.Object imgURL_;
    /**
     * <code>optional string imgURL = 9;</code>
     *
     * <pre>
     * 用户头像URL
     * </pre>
     */
    public java.lang.String getImgURL() {
      java.lang.Object ref = imgURL_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          imgURL_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string imgURL = 9;</code>
     *
     * <pre>
     * 用户头像URL
     * </pre>
     */
    public com.google.protobuf.ByteString
        getImgURLBytes() {
      java.lang.Object ref = imgURL_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imgURL_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 10;
    private volatile java.lang.Object username_;
    /**
     * <code>optional string username = 10;</code>
     *
     * <pre>
     * 用户名称
     * </pre>
     */
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          username_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string username = 10;</code>
     *
     * <pre>
     * 用户名称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LEVELINFO_FIELD_NUMBER = 12;
    private com.blemobi.sep.probuf.AccountProtos.PLevelInfo levelInfo_;
    /**
     * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
     *
     * <pre>
     * 会员等级信息
     * </pre>
     */
    public boolean hasLevelInfo() {
      return levelInfo_ != null;
    }
    /**
     * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
     *
     * <pre>
     * 会员等级信息
     * </pre>
     */
    public com.blemobi.sep.probuf.AccountProtos.PLevelInfo getLevelInfo() {
      return levelInfo_ == null ? com.blemobi.sep.probuf.AccountProtos.PLevelInfo.getDefaultInstance() : levelInfo_;
    }
    /**
     * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
     *
     * <pre>
     * 会员等级信息
     * </pre>
     */
    public com.blemobi.sep.probuf.AccountProtos.PLevelInfoOrBuilder getLevelInfoOrBuilder() {
      return getLevelInfo();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (forceBindPhone_ != false) {
        output.writeBool(4, forceBindPhone_);
      }
      if (newUser_ != false) {
        output.writeBool(5, newUser_);
      }
      if (!getUuidBytes().isEmpty()) {
        output.writeBytes(6, getUuidBytes());
      }
      if (!getTokenBytes().isEmpty()) {
        output.writeBytes(7, getTokenBytes());
      }
      if (!getNicknameBytes().isEmpty()) {
        output.writeBytes(8, getNicknameBytes());
      }
      if (!getImgURLBytes().isEmpty()) {
        output.writeBytes(9, getImgURLBytes());
      }
      if (!getUsernameBytes().isEmpty()) {
        output.writeBytes(10, getUsernameBytes());
      }
      if (levelInfo_ != null) {
        output.writeMessage(12, getLevelInfo());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (forceBindPhone_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, forceBindPhone_);
      }
      if (newUser_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, newUser_);
      }
      if (!getUuidBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getUuidBytes());
      }
      if (!getTokenBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getTokenBytes());
      }
      if (!getNicknameBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getNicknameBytes());
      }
      if (!getImgURLBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getImgURLBytes());
      }
      if (!getUsernameBytes().isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, getUsernameBytes());
      }
      if (levelInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getLevelInfo());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.blemobi.sep.probuf.LoginProtos.PLogin parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.LoginProtos.PLogin parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.LoginProtos.PLogin parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.LoginProtos.PLogin parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.LoginProtos.PLogin parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.LoginProtos.PLogin parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.LoginProtos.PLogin parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.blemobi.sep.probuf.LoginProtos.PLogin parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.LoginProtos.PLogin parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.LoginProtos.PLogin parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blemobi.sep.probuf.LoginProtos.PLogin prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bbproto.PLogin}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bbproto.PLogin)
        com.blemobi.sep.probuf.LoginProtos.PLoginOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blemobi.sep.probuf.LoginProtos.internal_static_bbproto_PLogin_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blemobi.sep.probuf.LoginProtos.internal_static_bbproto_PLogin_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blemobi.sep.probuf.LoginProtos.PLogin.class, com.blemobi.sep.probuf.LoginProtos.PLogin.Builder.class);
      }

      // Construct using com.blemobi.sep.probuf.LoginProtos.PLogin.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        forceBindPhone_ = false;

        newUser_ = false;

        uuid_ = "";

        token_ = "";

        nickname_ = "";

        imgURL_ = "";

        username_ = "";

        if (levelInfoBuilder_ == null) {
          levelInfo_ = null;
        } else {
          levelInfo_ = null;
          levelInfoBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blemobi.sep.probuf.LoginProtos.internal_static_bbproto_PLogin_descriptor;
      }

      public com.blemobi.sep.probuf.LoginProtos.PLogin getDefaultInstanceForType() {
        return com.blemobi.sep.probuf.LoginProtos.PLogin.getDefaultInstance();
      }

      public com.blemobi.sep.probuf.LoginProtos.PLogin build() {
        com.blemobi.sep.probuf.LoginProtos.PLogin result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blemobi.sep.probuf.LoginProtos.PLogin buildPartial() {
        com.blemobi.sep.probuf.LoginProtos.PLogin result = new com.blemobi.sep.probuf.LoginProtos.PLogin(this);
        result.forceBindPhone_ = forceBindPhone_;
        result.newUser_ = newUser_;
        result.uuid_ = uuid_;
        result.token_ = token_;
        result.nickname_ = nickname_;
        result.imgURL_ = imgURL_;
        result.username_ = username_;
        if (levelInfoBuilder_ == null) {
          result.levelInfo_ = levelInfo_;
        } else {
          result.levelInfo_ = levelInfoBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blemobi.sep.probuf.LoginProtos.PLogin) {
          return mergeFrom((com.blemobi.sep.probuf.LoginProtos.PLogin)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blemobi.sep.probuf.LoginProtos.PLogin other) {
        if (other == com.blemobi.sep.probuf.LoginProtos.PLogin.getDefaultInstance()) return this;
        if (other.getForceBindPhone() != false) {
          setForceBindPhone(other.getForceBindPhone());
        }
        if (other.getNewUser() != false) {
          setNewUser(other.getNewUser());
        }
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          onChanged();
        }
        if (!other.getToken().isEmpty()) {
          token_ = other.token_;
          onChanged();
        }
        if (!other.getNickname().isEmpty()) {
          nickname_ = other.nickname_;
          onChanged();
        }
        if (!other.getImgURL().isEmpty()) {
          imgURL_ = other.imgURL_;
          onChanged();
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          onChanged();
        }
        if (other.hasLevelInfo()) {
          mergeLevelInfo(other.getLevelInfo());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blemobi.sep.probuf.LoginProtos.PLogin parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blemobi.sep.probuf.LoginProtos.PLogin) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean forceBindPhone_ ;
      /**
       * <code>optional bool forceBindPhone = 4;</code>
       *
       * <pre>
       * 用户是否需要强制绑定手机号码，如果是，则需要绑定手机号码
       * </pre>
       */
      public boolean getForceBindPhone() {
        return forceBindPhone_;
      }
      /**
       * <code>optional bool forceBindPhone = 4;</code>
       *
       * <pre>
       * 用户是否需要强制绑定手机号码，如果是，则需要绑定手机号码
       * </pre>
       */
      public Builder setForceBindPhone(boolean value) {
        
        forceBindPhone_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool forceBindPhone = 4;</code>
       *
       * <pre>
       * 用户是否需要强制绑定手机号码，如果是，则需要绑定手机号码
       * </pre>
       */
      public Builder clearForceBindPhone() {
        
        forceBindPhone_ = false;
        onChanged();
        return this;
      }

      private boolean newUser_ ;
      /**
       * <code>optional bool newUser = 5;</code>
       *
       * <pre>
       * 是否新注册用户标识，true为新用户，false为老用户
       * </pre>
       */
      public boolean getNewUser() {
        return newUser_;
      }
      /**
       * <code>optional bool newUser = 5;</code>
       *
       * <pre>
       * 是否新注册用户标识，true为新用户，false为老用户
       * </pre>
       */
      public Builder setNewUser(boolean value) {
        
        newUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool newUser = 5;</code>
       *
       * <pre>
       * 是否新注册用户标识，true为新用户，false为老用户
       * </pre>
       */
      public Builder clearNewUser() {
        
        newUser_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object uuid_ = "";
      /**
       * <code>optional string uuid = 6;</code>
       *
       * <pre>
       * 用户ID
       * </pre>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string uuid = 6;</code>
       *
       * <pre>
       * 用户ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string uuid = 6;</code>
       *
       * <pre>
       * 用户ID
       * </pre>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 6;</code>
       *
       * <pre>
       * 用户ID
       * </pre>
       */
      public Builder clearUuid() {
        
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <code>optional string uuid = 6;</code>
       *
       * <pre>
       * 用户ID
       * </pre>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object token_ = "";
      /**
       * <code>optional string token = 7;</code>
       *
       * <pre>
       * 统一访问令牌
       * </pre>
       */
      public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            token_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string token = 7;</code>
       *
       * <pre>
       * 统一访问令牌
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          token_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string token = 7;</code>
       *
       * <pre>
       * 统一访问令牌
       * </pre>
       */
      public Builder setToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 7;</code>
       *
       * <pre>
       * 统一访问令牌
       * </pre>
       */
      public Builder clearToken() {
        
        token_ = getDefaultInstance().getToken();
        onChanged();
        return this;
      }
      /**
       * <code>optional string token = 7;</code>
       *
       * <pre>
       * 统一访问令牌
       * </pre>
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        token_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickname_ = "";
      /**
       * <code>optional string nickname = 8;</code>
       *
       * <pre>
       * 用户昵称
       * </pre>
       */
      public java.lang.String getNickname() {
        java.lang.Object ref = nickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            nickname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string nickname = 8;</code>
       *
       * <pre>
       * 用户昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNicknameBytes() {
        java.lang.Object ref = nickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string nickname = 8;</code>
       *
       * <pre>
       * 用户昵称
       * </pre>
       */
      public Builder setNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 8;</code>
       *
       * <pre>
       * 用户昵称
       * </pre>
       */
      public Builder clearNickname() {
        
        nickname_ = getDefaultInstance().getNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string nickname = 8;</code>
       *
       * <pre>
       * 用户昵称
       * </pre>
       */
      public Builder setNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object imgURL_ = "";
      /**
       * <code>optional string imgURL = 9;</code>
       *
       * <pre>
       * 用户头像URL
       * </pre>
       */
      public java.lang.String getImgURL() {
        java.lang.Object ref = imgURL_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            imgURL_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string imgURL = 9;</code>
       *
       * <pre>
       * 用户头像URL
       * </pre>
       */
      public com.google.protobuf.ByteString
          getImgURLBytes() {
        java.lang.Object ref = imgURL_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          imgURL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string imgURL = 9;</code>
       *
       * <pre>
       * 用户头像URL
       * </pre>
       */
      public Builder setImgURL(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imgURL_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string imgURL = 9;</code>
       *
       * <pre>
       * 用户头像URL
       * </pre>
       */
      public Builder clearImgURL() {
        
        imgURL_ = getDefaultInstance().getImgURL();
        onChanged();
        return this;
      }
      /**
       * <code>optional string imgURL = 9;</code>
       *
       * <pre>
       * 用户头像URL
       * </pre>
       */
      public Builder setImgURLBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imgURL_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>optional string username = 10;</code>
       *
       * <pre>
       * 用户名称
       * </pre>
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            username_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string username = 10;</code>
       *
       * <pre>
       * 用户名称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string username = 10;</code>
       *
       * <pre>
       * 用户名称
       * </pre>
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 10;</code>
       *
       * <pre>
       * 用户名称
       * </pre>
       */
      public Builder clearUsername() {
        
        username_ = getDefaultInstance().getUsername();
        onChanged();
        return this;
      }
      /**
       * <code>optional string username = 10;</code>
       *
       * <pre>
       * 用户名称
       * </pre>
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        username_ = value;
        onChanged();
        return this;
      }

      private com.blemobi.sep.probuf.AccountProtos.PLevelInfo levelInfo_ = null;
      private com.google.protobuf.SingleFieldBuilder<
          com.blemobi.sep.probuf.AccountProtos.PLevelInfo, com.blemobi.sep.probuf.AccountProtos.PLevelInfo.Builder, com.blemobi.sep.probuf.AccountProtos.PLevelInfoOrBuilder> levelInfoBuilder_;
      /**
       * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
       *
       * <pre>
       * 会员等级信息
       * </pre>
       */
      public boolean hasLevelInfo() {
        return levelInfoBuilder_ != null || levelInfo_ != null;
      }
      /**
       * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
       *
       * <pre>
       * 会员等级信息
       * </pre>
       */
      public com.blemobi.sep.probuf.AccountProtos.PLevelInfo getLevelInfo() {
        if (levelInfoBuilder_ == null) {
          return levelInfo_ == null ? com.blemobi.sep.probuf.AccountProtos.PLevelInfo.getDefaultInstance() : levelInfo_;
        } else {
          return levelInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
       *
       * <pre>
       * 会员等级信息
       * </pre>
       */
      public Builder setLevelInfo(com.blemobi.sep.probuf.AccountProtos.PLevelInfo value) {
        if (levelInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          levelInfo_ = value;
          onChanged();
        } else {
          levelInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
       *
       * <pre>
       * 会员等级信息
       * </pre>
       */
      public Builder setLevelInfo(
          com.blemobi.sep.probuf.AccountProtos.PLevelInfo.Builder builderForValue) {
        if (levelInfoBuilder_ == null) {
          levelInfo_ = builderForValue.build();
          onChanged();
        } else {
          levelInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
       *
       * <pre>
       * 会员等级信息
       * </pre>
       */
      public Builder mergeLevelInfo(com.blemobi.sep.probuf.AccountProtos.PLevelInfo value) {
        if (levelInfoBuilder_ == null) {
          if (levelInfo_ != null) {
            levelInfo_ =
              com.blemobi.sep.probuf.AccountProtos.PLevelInfo.newBuilder(levelInfo_).mergeFrom(value).buildPartial();
          } else {
            levelInfo_ = value;
          }
          onChanged();
        } else {
          levelInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
       *
       * <pre>
       * 会员等级信息
       * </pre>
       */
      public Builder clearLevelInfo() {
        if (levelInfoBuilder_ == null) {
          levelInfo_ = null;
          onChanged();
        } else {
          levelInfo_ = null;
          levelInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
       *
       * <pre>
       * 会员等级信息
       * </pre>
       */
      public com.blemobi.sep.probuf.AccountProtos.PLevelInfo.Builder getLevelInfoBuilder() {
        
        onChanged();
        return getLevelInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
       *
       * <pre>
       * 会员等级信息
       * </pre>
       */
      public com.blemobi.sep.probuf.AccountProtos.PLevelInfoOrBuilder getLevelInfoOrBuilder() {
        if (levelInfoBuilder_ != null) {
          return levelInfoBuilder_.getMessageOrBuilder();
        } else {
          return levelInfo_ == null ?
              com.blemobi.sep.probuf.AccountProtos.PLevelInfo.getDefaultInstance() : levelInfo_;
        }
      }
      /**
       * <code>optional .bbproto.PLevelInfo levelInfo = 12;</code>
       *
       * <pre>
       * 会员等级信息
       * </pre>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.blemobi.sep.probuf.AccountProtos.PLevelInfo, com.blemobi.sep.probuf.AccountProtos.PLevelInfo.Builder, com.blemobi.sep.probuf.AccountProtos.PLevelInfoOrBuilder> 
          getLevelInfoFieldBuilder() {
        if (levelInfoBuilder_ == null) {
          levelInfoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.blemobi.sep.probuf.AccountProtos.PLevelInfo, com.blemobi.sep.probuf.AccountProtos.PLevelInfo.Builder, com.blemobi.sep.probuf.AccountProtos.PLevelInfoOrBuilder>(
                  getLevelInfo(),
                  getParentForChildren(),
                  isClean());
          levelInfo_ = null;
        }
        return levelInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bbproto.PLogin)
    }

    // @@protoc_insertion_point(class_scope:bbproto.PLogin)
    private static final com.blemobi.sep.probuf.LoginProtos.PLogin DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blemobi.sep.probuf.LoginProtos.PLogin();
    }

    public static com.blemobi.sep.probuf.LoginProtos.PLogin getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PLogin> PARSER =
        new com.google.protobuf.AbstractParser<PLogin>() {
      public PLogin parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PLogin(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PLogin> getParserForType() {
      return PARSER;
    }

    public com.blemobi.sep.probuf.LoginProtos.PLogin getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bbproto_PLogin_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bbproto_PLogin_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013login.proto\022\007bbproto\032\raccount.proto\"\252\001" +
      "\n\006PLogin\022\026\n\016forceBindPhone\030\004 \001(\010\022\017\n\007newU" +
      "ser\030\005 \001(\010\022\014\n\004uuid\030\006 \001(\t\022\r\n\005token\030\007 \001(\t\022\020" +
      "\n\010nickname\030\010 \001(\t\022\016\n\006imgURL\030\t \001(\t\022\020\n\010user" +
      "name\030\n \001(\t\022&\n\tlevelInfo\030\014 \001(\0132\023.bbproto." +
      "PLevelInfoB%\n\026com.blemobi.sep.probufB\013Lo" +
      "ginProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.blemobi.sep.probuf.AccountProtos.getDescriptor(),
        }, assigner);
    internal_static_bbproto_PLogin_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bbproto_PLogin_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bbproto_PLogin_descriptor,
        new java.lang.String[] { "ForceBindPhone", "NewUser", "Uuid", "Token", "Nickname", "ImgURL", "Username", "LevelInfo", });
    com.blemobi.sep.probuf.AccountProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
