// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: news_inside.proto

package com.blemobi.sep.probuf;

public final class NewsApiProtos {
  private NewsApiProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PNewsUserStatisticOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bbproto.PNewsUserStatistic)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 FollowCount = 2;</code>
     *
     * <pre>
     * 关注用户总数
     * </pre>
     */
    int getFollowCount();

    /**
     * <code>optional int32 FansCount = 3;</code>
     *
     * <pre>
     * 粉丝用户总数
     * </pre>
     */
    int getFansCount();

    /**
     * <code>optional int32 TxtPostCount = 4;</code>
     *
     * <pre>
     * 文字帖的个数
     * </pre>
     */
    int getTxtPostCount();

    /**
     * <code>optional int32 ImgPostCount = 5;</code>
     *
     * <pre>
     * 图片帖的个数
     * </pre>
     */
    int getImgPostCount();

    /**
     * <code>optional int32 AudioPostCount = 6;</code>
     *
     * <pre>
     * 音频帖的个数
     * </pre>
     */
    int getAudioPostCount();

    /**
     * <code>optional int32 VideoPostCount = 7;</code>
     *
     * <pre>
     * 视频帖的个数
     * </pre>
     */
    int getVideoPostCount();

    /**
     * <code>optional int32 FollowShip = 8;</code>
     *
     * <pre>
     * 两用户间的关系、0:无关系，1,：是粉丝，2：已关注，3：相互关注
     * </pre>
     */
    int getFollowShip();
  }
  /**
   * Protobuf type {@code bbproto.PNewsUserStatistic}
   *
   * <pre>
   * 个人统计信息
   * </pre>
   */
  public  static final class PNewsUserStatistic extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:bbproto.PNewsUserStatistic)
      PNewsUserStatisticOrBuilder {
    // Use PNewsUserStatistic.newBuilder() to construct.
    private PNewsUserStatistic(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PNewsUserStatistic() {
      followCount_ = 0;
      fansCount_ = 0;
      txtPostCount_ = 0;
      imgPostCount_ = 0;
      audioPostCount_ = 0;
      videoPostCount_ = 0;
      followShip_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private PNewsUserStatistic(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 16: {

              followCount_ = input.readInt32();
              break;
            }
            case 24: {

              fansCount_ = input.readInt32();
              break;
            }
            case 32: {

              txtPostCount_ = input.readInt32();
              break;
            }
            case 40: {

              imgPostCount_ = input.readInt32();
              break;
            }
            case 48: {

              audioPostCount_ = input.readInt32();
              break;
            }
            case 56: {

              videoPostCount_ = input.readInt32();
              break;
            }
            case 64: {

              followShip_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.blemobi.sep.probuf.NewsApiProtos.internal_static_bbproto_PNewsUserStatistic_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.blemobi.sep.probuf.NewsApiProtos.internal_static_bbproto_PNewsUserStatistic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic.class, com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic.Builder.class);
    }

    public static final int FOLLOWCOUNT_FIELD_NUMBER = 2;
    private int followCount_;
    /**
     * <code>optional int32 FollowCount = 2;</code>
     *
     * <pre>
     * 关注用户总数
     * </pre>
     */
    public int getFollowCount() {
      return followCount_;
    }

    public static final int FANSCOUNT_FIELD_NUMBER = 3;
    private int fansCount_;
    /**
     * <code>optional int32 FansCount = 3;</code>
     *
     * <pre>
     * 粉丝用户总数
     * </pre>
     */
    public int getFansCount() {
      return fansCount_;
    }

    public static final int TXTPOSTCOUNT_FIELD_NUMBER = 4;
    private int txtPostCount_;
    /**
     * <code>optional int32 TxtPostCount = 4;</code>
     *
     * <pre>
     * 文字帖的个数
     * </pre>
     */
    public int getTxtPostCount() {
      return txtPostCount_;
    }

    public static final int IMGPOSTCOUNT_FIELD_NUMBER = 5;
    private int imgPostCount_;
    /**
     * <code>optional int32 ImgPostCount = 5;</code>
     *
     * <pre>
     * 图片帖的个数
     * </pre>
     */
    public int getImgPostCount() {
      return imgPostCount_;
    }

    public static final int AUDIOPOSTCOUNT_FIELD_NUMBER = 6;
    private int audioPostCount_;
    /**
     * <code>optional int32 AudioPostCount = 6;</code>
     *
     * <pre>
     * 音频帖的个数
     * </pre>
     */
    public int getAudioPostCount() {
      return audioPostCount_;
    }

    public static final int VIDEOPOSTCOUNT_FIELD_NUMBER = 7;
    private int videoPostCount_;
    /**
     * <code>optional int32 VideoPostCount = 7;</code>
     *
     * <pre>
     * 视频帖的个数
     * </pre>
     */
    public int getVideoPostCount() {
      return videoPostCount_;
    }

    public static final int FOLLOWSHIP_FIELD_NUMBER = 8;
    private int followShip_;
    /**
     * <code>optional int32 FollowShip = 8;</code>
     *
     * <pre>
     * 两用户间的关系、0:无关系，1,：是粉丝，2：已关注，3：相互关注
     * </pre>
     */
    public int getFollowShip() {
      return followShip_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (followCount_ != 0) {
        output.writeInt32(2, followCount_);
      }
      if (fansCount_ != 0) {
        output.writeInt32(3, fansCount_);
      }
      if (txtPostCount_ != 0) {
        output.writeInt32(4, txtPostCount_);
      }
      if (imgPostCount_ != 0) {
        output.writeInt32(5, imgPostCount_);
      }
      if (audioPostCount_ != 0) {
        output.writeInt32(6, audioPostCount_);
      }
      if (videoPostCount_ != 0) {
        output.writeInt32(7, videoPostCount_);
      }
      if (followShip_ != 0) {
        output.writeInt32(8, followShip_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (followCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, followCount_);
      }
      if (fansCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, fansCount_);
      }
      if (txtPostCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, txtPostCount_);
      }
      if (imgPostCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, imgPostCount_);
      }
      if (audioPostCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, audioPostCount_);
      }
      if (videoPostCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, videoPostCount_);
      }
      if (followShip_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, followShip_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bbproto.PNewsUserStatistic}
     *
     * <pre>
     * 个人统计信息
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bbproto.PNewsUserStatistic)
        com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatisticOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.blemobi.sep.probuf.NewsApiProtos.internal_static_bbproto_PNewsUserStatistic_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.blemobi.sep.probuf.NewsApiProtos.internal_static_bbproto_PNewsUserStatistic_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic.class, com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic.Builder.class);
      }

      // Construct using com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        followCount_ = 0;

        fansCount_ = 0;

        txtPostCount_ = 0;

        imgPostCount_ = 0;

        audioPostCount_ = 0;

        videoPostCount_ = 0;

        followShip_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.blemobi.sep.probuf.NewsApiProtos.internal_static_bbproto_PNewsUserStatistic_descriptor;
      }

      public com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic getDefaultInstanceForType() {
        return com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic.getDefaultInstance();
      }

      public com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic build() {
        com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic buildPartial() {
        com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic result = new com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic(this);
        result.followCount_ = followCount_;
        result.fansCount_ = fansCount_;
        result.txtPostCount_ = txtPostCount_;
        result.imgPostCount_ = imgPostCount_;
        result.audioPostCount_ = audioPostCount_;
        result.videoPostCount_ = videoPostCount_;
        result.followShip_ = followShip_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic) {
          return mergeFrom((com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic other) {
        if (other == com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic.getDefaultInstance()) return this;
        if (other.getFollowCount() != 0) {
          setFollowCount(other.getFollowCount());
        }
        if (other.getFansCount() != 0) {
          setFansCount(other.getFansCount());
        }
        if (other.getTxtPostCount() != 0) {
          setTxtPostCount(other.getTxtPostCount());
        }
        if (other.getImgPostCount() != 0) {
          setImgPostCount(other.getImgPostCount());
        }
        if (other.getAudioPostCount() != 0) {
          setAudioPostCount(other.getAudioPostCount());
        }
        if (other.getVideoPostCount() != 0) {
          setVideoPostCount(other.getVideoPostCount());
        }
        if (other.getFollowShip() != 0) {
          setFollowShip(other.getFollowShip());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int followCount_ ;
      /**
       * <code>optional int32 FollowCount = 2;</code>
       *
       * <pre>
       * 关注用户总数
       * </pre>
       */
      public int getFollowCount() {
        return followCount_;
      }
      /**
       * <code>optional int32 FollowCount = 2;</code>
       *
       * <pre>
       * 关注用户总数
       * </pre>
       */
      public Builder setFollowCount(int value) {
        
        followCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 FollowCount = 2;</code>
       *
       * <pre>
       * 关注用户总数
       * </pre>
       */
      public Builder clearFollowCount() {
        
        followCount_ = 0;
        onChanged();
        return this;
      }

      private int fansCount_ ;
      /**
       * <code>optional int32 FansCount = 3;</code>
       *
       * <pre>
       * 粉丝用户总数
       * </pre>
       */
      public int getFansCount() {
        return fansCount_;
      }
      /**
       * <code>optional int32 FansCount = 3;</code>
       *
       * <pre>
       * 粉丝用户总数
       * </pre>
       */
      public Builder setFansCount(int value) {
        
        fansCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 FansCount = 3;</code>
       *
       * <pre>
       * 粉丝用户总数
       * </pre>
       */
      public Builder clearFansCount() {
        
        fansCount_ = 0;
        onChanged();
        return this;
      }

      private int txtPostCount_ ;
      /**
       * <code>optional int32 TxtPostCount = 4;</code>
       *
       * <pre>
       * 文字帖的个数
       * </pre>
       */
      public int getTxtPostCount() {
        return txtPostCount_;
      }
      /**
       * <code>optional int32 TxtPostCount = 4;</code>
       *
       * <pre>
       * 文字帖的个数
       * </pre>
       */
      public Builder setTxtPostCount(int value) {
        
        txtPostCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 TxtPostCount = 4;</code>
       *
       * <pre>
       * 文字帖的个数
       * </pre>
       */
      public Builder clearTxtPostCount() {
        
        txtPostCount_ = 0;
        onChanged();
        return this;
      }

      private int imgPostCount_ ;
      /**
       * <code>optional int32 ImgPostCount = 5;</code>
       *
       * <pre>
       * 图片帖的个数
       * </pre>
       */
      public int getImgPostCount() {
        return imgPostCount_;
      }
      /**
       * <code>optional int32 ImgPostCount = 5;</code>
       *
       * <pre>
       * 图片帖的个数
       * </pre>
       */
      public Builder setImgPostCount(int value) {
        
        imgPostCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 ImgPostCount = 5;</code>
       *
       * <pre>
       * 图片帖的个数
       * </pre>
       */
      public Builder clearImgPostCount() {
        
        imgPostCount_ = 0;
        onChanged();
        return this;
      }

      private int audioPostCount_ ;
      /**
       * <code>optional int32 AudioPostCount = 6;</code>
       *
       * <pre>
       * 音频帖的个数
       * </pre>
       */
      public int getAudioPostCount() {
        return audioPostCount_;
      }
      /**
       * <code>optional int32 AudioPostCount = 6;</code>
       *
       * <pre>
       * 音频帖的个数
       * </pre>
       */
      public Builder setAudioPostCount(int value) {
        
        audioPostCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 AudioPostCount = 6;</code>
       *
       * <pre>
       * 音频帖的个数
       * </pre>
       */
      public Builder clearAudioPostCount() {
        
        audioPostCount_ = 0;
        onChanged();
        return this;
      }

      private int videoPostCount_ ;
      /**
       * <code>optional int32 VideoPostCount = 7;</code>
       *
       * <pre>
       * 视频帖的个数
       * </pre>
       */
      public int getVideoPostCount() {
        return videoPostCount_;
      }
      /**
       * <code>optional int32 VideoPostCount = 7;</code>
       *
       * <pre>
       * 视频帖的个数
       * </pre>
       */
      public Builder setVideoPostCount(int value) {
        
        videoPostCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 VideoPostCount = 7;</code>
       *
       * <pre>
       * 视频帖的个数
       * </pre>
       */
      public Builder clearVideoPostCount() {
        
        videoPostCount_ = 0;
        onChanged();
        return this;
      }

      private int followShip_ ;
      /**
       * <code>optional int32 FollowShip = 8;</code>
       *
       * <pre>
       * 两用户间的关系、0:无关系，1,：是粉丝，2：已关注，3：相互关注
       * </pre>
       */
      public int getFollowShip() {
        return followShip_;
      }
      /**
       * <code>optional int32 FollowShip = 8;</code>
       *
       * <pre>
       * 两用户间的关系、0:无关系，1,：是粉丝，2：已关注，3：相互关注
       * </pre>
       */
      public Builder setFollowShip(int value) {
        
        followShip_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 FollowShip = 8;</code>
       *
       * <pre>
       * 两用户间的关系、0:无关系，1,：是粉丝，2：已关注，3：相互关注
       * </pre>
       */
      public Builder clearFollowShip() {
        
        followShip_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:bbproto.PNewsUserStatistic)
    }

    // @@protoc_insertion_point(class_scope:bbproto.PNewsUserStatistic)
    private static final com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic();
    }

    public static com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PNewsUserStatistic>
        PARSER = new com.google.protobuf.AbstractParser<PNewsUserStatistic>() {
      public PNewsUserStatistic parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new PNewsUserStatistic(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<PNewsUserStatistic> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PNewsUserStatistic> getParserForType() {
      return PARSER;
    }

    public com.blemobi.sep.probuf.NewsApiProtos.PNewsUserStatistic getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_bbproto_PNewsUserStatistic_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_bbproto_PNewsUserStatistic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021news_inside.proto\022\007bbproto\032\nnews.proto" +
      "\032\023common_inside.proto\"\254\001\n\022PNewsUserStati" +
      "stic\022\023\n\013FollowCount\030\002 \001(\005\022\021\n\tFansCount\030\003" +
      " \001(\005\022\024\n\014TxtPostCount\030\004 \001(\005\022\024\n\014ImgPostCou" +
      "nt\030\005 \001(\005\022\026\n\016AudioPostCount\030\006 \001(\005\022\026\n\016Vide" +
      "oPostCount\030\007 \001(\005\022\022\n\nFollowShip\030\010 \001(\0052\324\002\n" +
      "\tIGrpcNews\0223\n\014GrpcPostEdit\022\022.bbproto.PPo" +
      "stInfo\032\017.bbproto.PEmpty\022:\n\014GrpcPostVote\022" +
      "\031.bbproto.PBetchVoteAction\032\017.bbproto.PEm" +
      "pty\022G\n\021GrpcPostVoteExist\022\031.bbproto.PBetc",
      "hVoteAction\032\027.bbproto.PNewsVoteExist\022>\n\016" +
      "GrpcNewsFollow\022\033.bbproto.PBetchFollowAct" +
      "ion\032\017.bbproto.PEmpty\022M\n\023GrpcNewsFollowEx" +
      "ist\022\033.bbproto.PBetchFollowAction\032\031.bbpro" +
      "to.PNewsFollowExistB\'\n\026com.blemobi.sep.p" +
      "robufB\rNewsApiProtosb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.blemobi.sep.probuf.NewsProtos.getDescriptor(),
          com.blemobi.sep.probuf.CommonApiProtos.getDescriptor(),
        }, assigner);
    internal_static_bbproto_PNewsUserStatistic_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bbproto_PNewsUserStatistic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_bbproto_PNewsUserStatistic_descriptor,
        new java.lang.String[] { "FollowCount", "FansCount", "TxtPostCount", "ImgPostCount", "AudioPostCount", "VideoPostCount", "FollowShip", });
    com.blemobi.sep.probuf.NewsProtos.getDescriptor();
    com.blemobi.sep.probuf.CommonApiProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
